# encoding: utf-8
# Energy companies seeds

more_companies = [{:interlocutore => 'Dotti / Basan',
 :canale_1 => 'Milano',
 :portale => :true,
 :compagnia => 'ITALIANA SYNKRONOS',
 :area => 'Energy',
 },
{:canale_1 => 'Direzione Milano',
 :portale => :true,
 :compagnia => 'TUA',
 :area => 'Energy',
 },
{:canale_1 => 'Dir. Milano',
 :compagnia => 'ZURICH',
 :interlocutore => 'Menapace / Provolo',
 :area => 'Energy',
 },
{:interlocutore => 'Zimatore',
 :compagnia => 'GENERALI INA ASSITALIA',
 :canale_1 => 'Gerenza Roma',
 :area => 'Energy',
 },
{:compagnia => 'AXA VERS.',
 :canale_1 => 'Wiass',
 :area => 'Energy',
 },
{:canale_1 => 'Direzione Milano',
 :compagnia => 'ITAS',
 :area => 'Energy',
 },
{:interlocutore => 'Francesca',
 :canale_1 => 'Zurigo',
 :compagnia => 'CATLIN',
 :area => 'Energy',
 },
{:note_operative => 'disponibili a quotare + convenzione
Italia quota con Danimarca e Londra',
 :canale_1 => 'Direzione Milano',
 :aggiornamento => DateTime.strptime('04/12/13', '%d/%m/%y'),
 :compagnia => 'CNA',
 :area => 'Energy',
 },
{:canale_1 => 'Londra',
 :compagnia => 'GCUBE',
 :area => 'Energy',
 },
{:interlocutore => 'Maini',
 :note_operative => 'da verificare operatività',
 :canale_1 => 'Direzione Padova',
 :compagnia => 'ALLIANZ',
 :area => 'Energy',
 },
]

more_companies.each do |company|
                   Company.create!(company)
end

# Technology companies seeds

more_companies = [{:interlocutore => 'Dotti / Basan',
 :canale_1 => 'Milano',
 :compagnia => 'ITALIANA SYNKRONOS',
 :portale => :true,
 :area => 'Technology',
 },
{:interlocutore => 'Menapace / Provolo',
 :canale_1 => 'Dir. Milano',
 :compagnia => 'ZURICH',
 :area => 'Technology',
 },
{:compagnia => 'ALLIANZ',
 :canale_1 => 'Direzione Padova',
 :interlocutore => 'Maini',
 :area => 'Technology',
 },
{:interlocutore => 'Fassina',
 :canale_1 => 'Direzione Padova',
 :compagnia => 'UNIPOL',
 :area => 'Technology',
 },
{:interlocutore => 'Zimatore',
 :canale_1 => 'Gerenza Roma',
 :compagnia => 'GENERALI INA ASSITALIA',
 :area => 'Technology',
 },
{:note_operative => 'Verificare apertura accordo',
 :interlocutore => 'Pane',
 :canale_1 => 'Gerenza Bologna',
 :compagnia => 'REALE MUTUA',
 :area => 'Technology',
 },
{:compagnia => 'ITAS',
 :canale_1 => 'Direzione Milano',
 :area => 'Technology',
 },
{:canale_1 => 'Direzione Milano',
 :compagnia => 'CATTOLICA',
 :interlocutore => 'Zilli',
 :note_operative => 'No riass x decennali postume',
 :area => 'Technology',
 },
{:canale_1 => 'Direzione Milano',
 :compagnia => 'FONDIARIA',
 :interlocutore => 'Guidi',
 :area => 'Technology',
 },
{:note_operative => 'Rischi >10mio',
 :compagnia => 'ACE',
 :canale_1 => 'Direzione Milano',
 :area => 'Technology',
 },
{:canale_1 => 'Direzione Milano',
 :compagnia => 'AIG',
 :note_operative => 'Rischi >100mio',
 :area => 'Technology',
 },
]

more_companies.each do |company|
                   Company.create!(company)
end

# Liability companies seeds

more_companies = [{:interlocutore => 'Menapace / Provolo',
 :canale_1 => 'Dir. Milano',
 :compagnia => 'ZURICH',
 :area => 'Liability',
 },
{:interlocutore => 'Maini',
 :note_operative => 'Rc anche con aziende fatturato inferiore 4mln
RcProdotti anche stand-alone',
 :compagnia => 'ALLIANZ',
 :canale_1 => 'Direzione Padova',
 :aggiornamento => DateTime.strptime('25/03/14', '%d/%m/%y'),
 :area => 'Liability',
 },
{:compagnia => 'UNIPOL',
 :canale_1 => 'Direzione Padova',
 :interlocutore => 'Fassina',
 :area => 'Liability',
 },
{:note_operative => 'No programmi internaz.
No automotive
RCP-RECALL: no indiretta, no diretta Usa/Can
RCP: no danni patrim. puri
pr.min.imp 5.000  In RCTOP no problem per retrocover USA; l\'export diretto USA non deve essere > 25% totale; premio minimo con export diretto Euro 15000; NO Automotive',
 :interlocutore => 'Pitton',
 :aggiornamento => DateTime.strptime('14/10/13', '%d/%m/%y'),
 :canale_1 => 'Direzione Milano',
 :compagnia => 'QBE',
 :area => 'Liability',
 },
{:interlocutore => 'Zimatore',
 :compagnia => 'GENERALI INA ASSITALIA',
 :canale_1 => 'Gerenza Roma',
 :area => 'Liability',
 },
{:interlocutore => 'Pane',
 :note_operative => 'Verificare apertura accordo
RCTOP no problem',
 :compagnia => 'REALE MUTUA',
 :canale_1 => 'Gerenza Bologna',
 :aggiornamento => DateTime.strptime('23/09/13', '%d/%m/%y'),
 :area => 'Liability',
 },
{:interlocutore => 'Cerretelli',
 :note_operative => 'Facility - capitolati completi x metalmecc e alimentari premio min imp 3.000
"Taylor made" pr.min.imp 20.000',
 :portale => :true,
 :compagnia => 'AXA',
 :canale_1 => 'Direzione Milano',
 :aggiornamento => DateTime.strptime('01/04/14', '%d/%m/%y'),
 :area => 'Liability',
 },
{:interlocutore => 'Furiati',
 :note_operative => 'Premio minimo Euro 3000 imp.li; massimo max concedibile Euro 10mio (aggregato RCTOP)',
 :compagnia => 'CATTOLICA',
 :canale_1 => 'Direzione Milano',
 :area => 'Liability',
 },
{:compagnia => ' ACE',
 :area => 'Liability',
 },
{:compagnia => 'AIG',
 :area => 'Liability',
 },
{:compagnia => 'CHUBB',
 :area => 'Liability',
 },
{:canale_1 => 'Direzione Milano',
 :compagnia => 'FONDIARIA',
 :interlocutore => 'Guidi',
 :area => 'Liability',
 },
{:compagnia => 'ITAS',
 :canale_1 => 'Direzione Milano',
 :area => 'Liability',
 },
]

more_companies.each do |company|
                   Company.create!(company)
end

# Bond companies seeds

more_companies = [{:compagnia => 'TUA ASS.NI',
 :portale => :true,
 :canale_1 => 'Direzione Milano',
 :provvigione => 20.00,
 :interlocutore => 'Braca',
 :area => 'Bond',
 },
{:provvigione => 14.00,
 :interlocutore => 'Marangio Kesten',
 :canale_2 => 'ag.Bologna',
 :canale_1 => 'Direzione Milano',
 :portale => :true,
 :compagnia => 'ELBA',
 :area => 'Bond',
 },
{:provvigione => 15.00,
 :interlocutore => 'Angelo De Benedetto',
 :note_operative => 'Iniiziato collaborazione nel 2014; efficacia da provare',
 :canale_1 => 'Milano',
 :compagnia => 'AM TRUST',
 :area => 'Bond',
 },
{:compagnia => 'GENERALI',
 :canale_1 => 'Tecnico Direzione',
 :canale_2 => 'Ag. Modena / Bologna',
 :provvigione => 9.00,
 :interlocutore => 'Schiappa-casse',
 :area => 'Bond',
 },
{:canale_1 => 'Direzione Milano',
 :compagnia => 'ZURICH',
 :interlocutore => 'Panigo',
 :provvigione => 15.00,
 :area => 'Bond',
 },
{:interlocutore => 'Pudda',
 :compagnia => 'ITAS',
 :canale_1 => 'Gerenza Milano',
 :area => 'Bond',
 },
{:canale_1 => 'Agenzia Bologna-Ferrara',
 :compagnia => 'ATRADIUS',
 :provvigione => 10.00,
 :interlocutore => 'Picciotto',
 :area => 'Bond',
 },
{:note_operative => 'NO Energie rinnovabili',
 :provvigione => 8.00,
 :interlocutore => 'Vanni / Emanuela',
 :canale_2 => '/ Ancona',
 :canale_1 => 'Agenzia Bologna S.Vitale',
 :compagnia => 'COFACE',
 :area => 'Bond',
 },
{:provvigione => 10.00,
 :interlocutore => 'Agostino',
 :compagnia => 'SACE BT',
 :canale_1 => 'Agenzia Pesaro',
 :area => 'Bond',
 },
{:interlocutore => 'Garofalo Berta',
 :provvigione => 15.00,
 :compagnia => 'FONDIARIA - SAI',
 :canale_1 => 'Direzione Milano',
 :area => 'Bond',
 },
{:provvigione => 15.00,
 :interlocutore => 'Moggia ??',
 :compagnia => 'ALLIANZ',
 :canale_1 => 'Direzione Padova',
 :area => 'Bond',
 },
{:provvigione => 15.00,
 :interlocutore => 'Sgarzi',
 :note_operative => 'per importi > € 25.000 almeno 15 gg x affidamento',
 :compagnia => 'REALE MUTUA',
 :canale_1 => 'Gerenza / Agenzia Bologna',
 :area => 'Bond',
 },
{:compagnia => 'INA ASSITALIA',
 :canale_1 => 'Ag. Bologna',
 :canale_2 => 'Ag. Cento',
 :provvigione => 12.00,
 :interlocutore => 'Cinelli',
 :area => 'Bond',
 },
{:canale_1 => 'Agenzia Vignola',
 :compagnia => 'VITTORIA',
 :provvigione => 11.00,
 :interlocutore => 'Magda - Moschetti',
 :canale_2 => 'Dir. Milano',
 :area => 'Bond',
 },
{:interlocutore => 'Franchin',
 :provvigione => 10.50,
 :compagnia => 'MILANO - SASA',
 :canale_1 => 'Direzione Trieste (ag. Modena)',
 :area => 'Bond',
 },
{:canale_1 => 'Modena',
 :compagnia => 'SACE',
 :note_operative => 'Solo energie rinnovabili
Compet. territoriale EMR e MARCHE',
 :interlocutore => 'Gherardi',
 :area => 'Bond',
 },
{:canale_1 => 'Roma',
 :compagnia => 'GABLE',
 :portale => :true,
 :area => 'Bond',
 },
{:compagnia => 'UNIPOL',
 :canale_1 => 'Direzione Padova',
 :interlocutore => 'Fassina Golfetto',
 :provvigione => 15.00,
 :area => 'Bond',
 },
{:provvigione => 10.50,
 :interlocutore => 'Scozza-rella',
 :portale => :true,
 :compagnia => 'LIGURIA',
 :canale_1 => 'Direzione Milano (ag. Modena)',
 :area => 'Bond',
 },
]

more_companies.each do |company|
                   Company.create!(company)
end

# Credit companies seeds

more_companies = [{:canale_2 => '/ Ancona',
 :interlocutore => 'Vanni / Emanuela',
 :compagnia => 'COFACE',
 :canale_1 => 'Agenzia Bologna S.Vitale',
 :area => 'Credit',
 },
{:canale_1 => 'Agenzia Bologna-Ferrara',
 :compagnia => 'ATRADIUS',
 :interlocutore => 'Picciotto',
 :area => 'Credit',
 },
{:canale_1 => 'Agenzia Pesaro',
 :compagnia => 'SACE BT',
 :interlocutore => 'Agostino',
 :area => 'Credit',
 },
{:canale_1 => 'Modena /Milano',
 :compagnia => 'SACE',
 :interlocutore => 'Gherardi',
 :area => 'Credit',
 },
{:compagnia => 'EULER',
 :canale_1 => 'Ag. Jesi (Novelli) / Modena (Ferranti-Creatura)',
 :canale_2 => 'Loredana Bombaci (Dir. PD)',
 :area => 'Credit',
 },
]

more_companies.each do |company|
                   Company.create!(company)
end

# Residential companies seeds

more_companies = [{:portale => :true,
 :compagnia => 'ZURICH',
 :canale_1 => 'Dir. Milano',
 :interlocutore => 'Menapace / Provolo',
 :note_operative => 'Sconto 20% (no su premio catastrofali)',
 :area => 'Residential',
 },
{:compagnia => 'ALLIANZ',
 :portale => :true,
 :canale_1 => 'Direzione Padova',
 :interlocutore => 'Maini',
 :area => 'Residential',
 },
{:interlocutore => 'Fassina',
 :portale => :true,
 :compagnia => 'UNIPOL',
 :canale_1 => 'Direzione Padova',
 :area => 'Residential',
 },
{:note_operative => 'disponibili x convenzione casa: garanzie aggiuntive concordate, con appendice',
 :aggiornamento => DateTime.strptime('06/02/13', '%d/%m/%y'),
 :canale_1 => 'Direzione Milano',
 :compagnia => 'TUA ASS.NI',
 :portale => :true,
 :area => 'Residential',
 },
{:note_operative => 'Verificare operatività',
 :interlocutore => '??',
 :compagnia => 'GENERALI TORO',
 :portale => :true,
 :canale_1 => 'Gerenza Bologna',
 :area => 'Residential',
 },
{:compagnia => 'REALE MUTUA',
 :canale_1 => 'Gerenza Bologna',
 :aggiornamento => DateTime.strptime('23/09/13', '%d/%m/%y'),
 :interlocutore => 'Pane',
 :note_operative => 'Verificare operatività
portale x retail 2014
Convenzioni…?',
 :area => 'Residential',
 },
{:interlocutore => 'Camilla Bassi',
 :canale_2 => 'Blue Underwriting',
 :canale_1 => 'Direzione Milano',
 :portale => :true,
 :compagnia => 'AIG',
 :area => 'Residential',
 },
{:canale_1 => 'Direzione Milano',
 :compagnia => 'ITAS',
 :area => 'Residential',
 },
]

more_companies.each do |company|
                   Company.create!(company)
end

# Property companies seeds

more_companies = [{:interlocutore => 'Menapace / Provolo',
 :note_operative => 'Sconto 20% (no su premio catastrofali)',
 :portale => :true,
 :compagnia => 'ZURICH',
 :canale_1 => 'Dir. Milano',
 :area => 'Property',
 },
{:compagnia => 'ALLIANZ',
 :portale => :true,
 :aggiornamento => DateTime.strptime('25/03/14', '%d/%m/%y'),
 :canale_1 => 'Direzione Padova',
 :note_operative => 'Valutazioni oculate: info per quotazione, poi sopralluogo, quindi conferma quotazione
Terremoto “con attenzione”',
 :interlocutore => 'Maini',
 :area => 'Property',
 },
{:interlocutore => 'Fassina',
 :compagnia => 'UNIPOL',
 :portale => :true,
 :canale_1 => 'Direzione Padova',
 :area => 'Property',
 },
{:interlocutore => 'Viterbori',
 :note_operative => 'No Food, Energy, Discariche
info tecniche: Questionari, Ispezioni altre comp., ispezione Qbe
Limiti: 150mln€',
 :canale_1 => 'Direzione Milano',
 :aggiornamento => DateTime.strptime('14/10/13', '%d/%m/%y'),
 :compagnia => 'QBE',
 :area => 'Property',
 },
{:interlocutore => 'Zimatore',
 :compagnia => 'GENERALI INA ASSITALIA',
 :canale_1 => 'Gerenza Roma',
 :area => 'Property',
 },
{:compagnia => 'REALE MUTUA',
 :aggiornamento => DateTime.strptime('23/09/13', '%d/%m/%y'),
 :canale_1 => 'Gerenza Bologna',
 :note_operative => 'Verificare apertura accordo
Somma assic. minimi 5mln contenuto: merci + macc/attr/arred
Attenzione Terremoto
Rapporto ispettivo (anche di altre compagnie)',
 :interlocutore => 'Pane',
 :area => 'Property',
 },
{:compagnia => 'AXA',
 :aggiornamento => DateTime.strptime('01/04/14', '%d/%m/%y'),
 :canale_1 => 'Direzione Milano',
 :premio_minimo => '5.000 imp facility
25.000 taylor made',
 :note_operative => 'Facility - capitolato completo: 2 griglie franchigie e limiti',
 :interlocutore => 'Cerretelli',
 :area => 'Property',
 },
{:canale_1 => 'Direzione Milano',
 :compagnia => 'CATTOLICA',
 :interlocutore => 'Catallo',
 :premio_minimo => '3.000 imp',
 :area => 'Property',
 },
{:interlocutore => 'Guidi',
 :compagnia => 'FONDIARIA',
 :canale_1 => 'Direzione Milano',
 :area => 'Property',
 },
{:canale_1 => 'Direzione Milano',
 :compagnia => 'ITAS',
 :area => 'Property',
 },
]

more_companies.each do |company|
                   Company.create!(company)
end

# Multirisk companies seeds

more_companies = [{:portale => :true,
 :compagnia => 'ZURICH',
 :canale_1 => 'Dir. Milano',
 :interlocutore => 'Menapace / Provolo',
 :area => 'Multirisk',
 },
{:compagnia => 'ALLIANZ',
 :portale => :true,
 :canale_1 => 'Direzione Padova',
 :interlocutore => 'Maini',
 :area => 'Multirisk',
 },
{:interlocutore => 'Fassina',
 :canale_1 => 'Direzione Padova',
 :portale => :true,
 :compagnia => 'UNIPOL',
 :area => 'Multirisk',
 },
{:compagnia => 'GENERALI INA ASSITALIA',
 :canale_1 => 'Gerenza Roma',
 :interlocutore => 'Zimatore',
 :area => 'Multirisk',
 },
{:compagnia => 'GENERALI TORO',
 :canale_1 => 'Gerenza Bologna',
 :note_operative => 'Verificare operatività',
 :area => 'Multirisk',
 },
{:interlocutore => 'Pane',
 :note_operative => 'Verificare apertura accordo',
 :canale_1 => 'Gerenza Bologna',
 :compagnia => 'REALE MUTUA',
 :area => 'Multirisk',
 },
{:compagnia => 'ITAS',
 :canale_1 => 'Direzione Milano',
 :area => 'Multirisk',
 },
{:compagnia => 'CATTOLICA',
 :canale_1 => 'Direzione Milano',
 :note_operative => 'Premio minimo Euro 3000 imp.li',
 :interlocutore => 'Catallo',
 :area => 'Multirisk',
 },
{:compagnia => 'FONDIARIA',
 :canale_1 => 'Direzione Milano',
 :interlocutore => 'Guidi',
 :area => 'Multirisk',
 },
]

more_companies.each do |company|
                   Company.create!(company)
end

# Marine companies seeds

more_companies = [{:interlocutore => 'Facchini',
 :compagnia => 'ACE',
 :canale_1 => 'Dir. Bologna',
 :area => 'Marine',
 },
{:interlocutore => 'Maini',
 :note_operative => 'Nel 2014 aggressivi: cargo',
 :canale_1 => 'Direzione Padova',
 :aggiornamento => DateTime.strptime('25/03/14', '%d/%m/%y'),
 :compagnia => 'ALLIANZ',
 :area => 'Marine',
 },
{:compagnia => 'AIG',
 :canale_1 => 'Dir. Milano',
 :area => 'Marine',
 },
{:interlocutore => 'Menapace / Provolo',
 :canale_1 => 'Dir. Milano',
 :compagnia => 'ZURICH',
 :area => 'Marine',
 },
{:interlocutore => 'Zimatore',
 :compagnia => 'GENERALI INA ASSITALIA',
 :canale_1 => 'Gerenza Roma',
 :area => 'Marine',
 },
{:canale_1 => 'Direzione Milano',
 :compagnia => 'CHUBB',
 :interlocutore => 'Angelo',
 :area => 'Marine',
 },
{:compagnia => 'CNA',
 :portale => :true,
 :aggiornamento => DateTime.strptime('04/12/13', '%d/%m/%y'),
 :canale_1 => 'Direzione Milano',
 :note_operative => 'Sì Cargo
No Rame, Caffè, Valori, FineArt, Corpi
Sì auto, moto
S&T: nominativi Estero, no nominativi in Italia
SI\' singoli certificati',
 :interlocutore => 'Fabiani',
 :area => 'Marine',
 },
]

more_companies.each do |company|
                   Company.create!(company)
end

# Health companies seeds

more_companies = [{:compagnia => 'ACE',
 :canale_1 => 'Dir. Bologna',
 :interlocutore => 'Facchino',
 :area => 'Health',
 },
{:note_operative => 'Corporate: varie possibilità di scelta x franchigia su IP
Retail: idem Corporate, inoltre polizza "Maxi" - 3 tagli fissi, bassi costi ma con franchigia 24% su IP e 66% su IPM, raddoppio indennizzo se IP uguale o superiore 50%, ADI assist.domicil.integrata',
 :aggiornamento => DateTime.strptime('06/02/13', '%d/%m/%y'),
 :canale_1 => 'Direzione Milano',
 :compagnia => 'TUA',
 :portale => :true,
 :area => 'Health',
 },
{:note_operative => 'Infortuni aziende aderenti a Confindustria (prodotto “Conferme”):
-       IP - Dirigenti 0,68‰ - € 1.000.000 senza franchigia
-       IP - Titolari/Amministratori 0,68‰ - € 300.000 senza franchigia
-       IPM – 1‰ fino 45 anni, 2‰ oltre 45 anni - € 500.000',
 :compagnia => 'ALLIANZ',
 :aggiornamento => DateTime.strptime('25/03/14', '%d/%m/%y'),
 :canale_1 => 'Direzione Padova',
 :area => 'Health',
 },
{:compagnia => 'ALLIANZ WORLD WIDE CARE',
 :aggiornamento => DateTime.strptime('25/03/14', '%d/%m/%y'),
 :note_operative => 'Infortuni contraenza personale per Imprenditori di aziende Confindustria: -       Allianz World Wide tramite “Cassa” x Infortuni e RSM',
 :area => 'Health',
 },
{:compagnia => 'AIG',
 :portale => :true,
 :canale_1 => 'Dir. Milano',
 :area => 'Health',
 },
{:interlocutore => 'Menapace / Provolo',
 :canale_1 => 'Dir. Milano',
 :compagnia => 'ZURICH',
 :area => 'Health',
 },
{:interlocutore => 'Zimatore',
 :compagnia => 'GENERALI INA ASSITALIA',
 :canale_1 => 'Gerenza Roma',
 :area => 'Health',
 },
{:compagnia => 'CHUBB',
 :canale_1 => 'Direzione Milano',
 :area => 'Health',
 },
{:compagnia => 'LLOYD\'S IO BROKER',
 :note_operative => 'Condizioni come da F.I. allegato. Clausola “Fine Carriera” come da allegato - 
Franchigia su IP min 3% relativa a 10% fino a €500.000 - Franchigie ipm – vedi tabella di polizza -  
Tassi Morte e IP da 0,70pro mille lordo -  
IPM da 1,30 (sotto i 30 non fumatori) a 2,85 (fumatori 60enni) -  
Limiti fino a €5.000.000 nessun rapporto tra capitali assicurati morte e IP -  
Premio minimo €500 -  
Questionari allegati.',
 :interlocutore => 'Vittorio Scala',
 :provvigione => 15.00,
 :area => 'Health',
 },
{:compagnia => 'LLOYD\'S RFIB / Stample Halla (shus ltd)',
 :provvigione => 18.00,
 :interlocutore => 'Enrico Nuzzo',
 :area => 'Health',
 },
]

more_companies.each do |company|
                   Company.create!(company)
end

# MinorHealth companies seeds

more_companies = [{:compagnia => 'METLIFE',
 :aggiornamento => DateTime.strptime('02/07/14', '%d/%m/%y'),
 :canale_1 => 'Dir. Milano',
 :note_operative => 'prodotto infortuni e malattia Metlife “ Protezione Junior” dedicato ai bambini di età compresa tra i 3 mesi e i 21 anni. ',
 :interlocutore => 'Zuddas',
 :area => 'MinorHealth',
 },
]

more_companies.each do |company|
                   Company.create!(company)
end

# Accident companies seeds

more_companies = [{:portale => :true,
 :compagnia => 'ACE',
 :canale_1 => 'Dir. Bologna',
 :interlocutore => '??',
 :area => 'Accident',
 },
]

more_companies.each do |company|
                   Company.create!(company)
end

# Life companies seeds

more_companies = [{:compagnia => 'ZURICH',
 :portale => :true,
 :canale_1 => 'Dir. Milano',
 :area => 'Life',
 },
{:compagnia => 'ALLIANZ',
 :canale_1 => 'Direzione milano',
 :area => 'Life',
 },
{:canale_1 => 'Direzione Milano',
 :compagnia => 'METLIFE',
 :portale => :true,
 :area => 'Life',
 },
{:canale_1 => 'Direzione Padova',
 :portale => :true,
 :compagnia => 'ACE',
 :area => 'Life',
 },
{:interlocutore => '???',
 :canale_1 => 'Direzione Milano',
 :compagnia => 'FONDIARIA',
 :area => 'Life',
 },
{:interlocutore => 'Carboni',
 :note_operative => 'Nel 2014 hanno budget con rappel importanti',
 :compagnia => 'AVIVA',
 :canale_1 => 'Agenzia Bologna',
 :area => 'Life',
 },
{:compagnia => 'UNIQA',
 :canale_1 => 'Agenzia Bologna',
 :area => 'Life',
 },
{:compagnia => 'PRAMERICA',
 :interlocutore => 'Francesco Napoli',
 :area => 'Life',
 },
{:compagnia => 'CATTOLICA PREVIDENZA',
 :portale => :true,
 :canale_1 => 'Direzione Milano',
 :area => 'Life',
 },
]

more_companies.each do |company|
                   Company.create!(company)
end

# Care companies seeds

more_companies = [{:note_operative => '??',
 :interlocutore => 'Menapace / Provolo',
 :canale_1 => 'Dir. Milano',
 :compagnia => 'ZURICH',
 :portale => :true,
 :area => 'Care',
 },
{:compagnia => 'ALLIANZ',
 :portale => :true,
 :canale_1 => 'Direzione milano',
 :area => 'Care',
 },
{:canale_1 => 'Direzione Milano',
 :compagnia => 'METLIFE (CASSA)',
 :portale => :true,
 :area => 'Care',
 },
{:canale_1 => 'Vittorio Scala',
 :compagnia => 'UNIASSIST (CASSA)',
 :note_operative => 'Adesione anche di Liberi Professionisti con P.IVA',
 :provvigione => 11.00,
 :area => 'Care',
 },
{:compagnia => 'FONDIARIA',
 :canale_1 => 'Direzione Milano',
 :interlocutore => '???',
 :area => 'Care',
 },
{:portale => :true,
 :compagnia => 'FILO DIRETTO',
 :canale_1 => 'Direzione Milano',
 :interlocutore => 'Carboni',
 :area => 'Care',
 },
{:compagnia => 'UNIQA',
 :canale_1 => 'Agenzia Bologna',
 :area => 'Care',
 },
{:canale_1 => 'Gerenza Bologna',
 :portale => :true,
 :compagnia => 'GENERALI ITALIA TORO',
 :note_operative => 'Verificare operatività canale comm.le',
 :area => 'Care',
 },
{:canale_1 => 'Dir. Roma',
 :compagnia => 'INA ASSITALIA',
 :interlocutore => 'Zimatore',
 :area => 'Care',
 },
{:compagnia => 'REALE MUTUA',
 :canale_1 => 'Gerenza Bologna',
 :note_operative => 'Verificare operatività',
 :interlocutore => 'Pane',
 :area => 'Care',
 },
{:note_operative => 'Verificare operatività canale comm.le',
 :interlocutore => '??',
 :compagnia => 'UNIQA',
 :canale_1 => 'Ag. Bologna',
 :area => 'Care',
 },
{:compagnia => 'UNISALUTE',
 :canale_1 => 'Dir. Bologna',
 :area => 'Care',
 },
{:note_operative => 'RSM new prodotto
LTC prodotto (provv 35%)',
 :canale_1 => 'Dir. Milano',
 :aggiornamento => DateTime.strptime('06/02/13', '%d/%m/%y'),
 :compagnia => 'TUA ASSICURAZIONI',
 :area => 'Care',
 },
]

more_companies.each do |company|
                   Company.create!(company)
end

# Technical companies seeds

more_companies = [{:interlocutore => 'Menapace / Provolo',
 :compagnia => 'ZURICH',
 :portale => :true,
 :canale_1 => 'Dir. Milano',
 :area => 'Technical',
 },
{:aggiornamento => DateTime.strptime('25/03/14', '%d/%m/%y'),
 :canale_1 => 'Direzione Padova',
 :compagnia => 'ALLIANZ',
 :portale => :true,
 :interlocutore => 'Maini',
 :area => 'Technical',
 },
{:interlocutore => 'Fassina',
 :compagnia => 'UNIPOL',
 :portale => :true,
 :canale_1 => 'Direzione Padova',
 :area => 'Technical',
 },
{:interlocutore => 'Zirano',
 :portale => :true,
 :compagnia => 'LLOYD\'S LINK',
 :area => 'Technical',
 },
{:canale_1 => 'Gerenza Roma',
 :portale => :true,
 :compagnia => 'LLOYD\'S AEC',
 :area => 'Technical',
 },
{:interlocutore => 'Pane',
 :note_operative => 'Verificare apertura accordo',
 :compagnia => 'REALE MUTUA',
 :canale_1 => 'Gerenza Bologna',
 :area => 'Technical',
 },
{:compagnia => 'LLOYD\'S UIA',
 :portale => :true,
 :canale_1 => 'Direzione Milano',
 :area => 'Technical',
 },
{:compagnia => 'DUAL',
 :canale_1 => 'Direzione Milano',
 :area => 'Technical',
 },
{:compagnia => 'TUA',
 :portale => :true,
 :aggiornamento => DateTime.strptime('06/02/13', '%d/%m/%y'),
 :note_operative => 'Rc professionale x Agronomi, Dipendenti Pubblici, Agenti Immobiliari, Mediatori Creditizi, Certificatori Energetici (oltre a Periti, Architetti, Ingegneri, Avvocati, Commercialisti)',
 :area => 'Technical',
 },
{:compagnia => ' ACE',
 :area => 'Technical',
 },
{:compagnia => 'AIG',
 :area => 'Technical',
 },
{:note_operative => 'Solo professioni atipiche non regolamentate',
 :premio_minimo => '1200',
 :aggiornamento => DateTime.strptime('04/12/13', '%d/%m/%y'),
 :compagnia => 'CNA',
 :area => 'Technical',
 },
{:aggiornamento => DateTime.strptime('14/10/13', '%d/%m/%y'),
 :compagnia => 'QBE',
 :interlocutore => 'Garlschè',
 :note_operative => 'Professioni tecniche di certificazione prodotti - Sì professioni non regolamentate
Sì professioni tecniche',
 :area => 'Technical',
 },
]

more_companies.each do |company|
                   Company.create!(company)
end

# Medical companies seeds

more_companies = [{:compagnia => 'ZURICH',
 :canale_1 => 'Dir. Milano',
 :interlocutore => 'Menapace / Provolo',
 :area => 'Medical',
 },
{:compagnia => 'ALLIANZ',
 :canale_1 => 'Direzione Padova',
 :interlocutore => 'Maini',
 :area => 'Medical',
 },
{:canale_1 => 'Direzione Padova',
 :compagnia => 'UNIPOL',
 :interlocutore => 'Fassina',
 :area => 'Medical',
 },
{:note_operative => '??',
 :compagnia => 'FONDIARIA',
 :area => 'Medical',
 },
{:canale_1 => 'Assimedici',
 :compagnia => 'ASS.CE MILANESE',
 :area => 'Medical',
 },
{:canale_1 => 'Direzione Milano',
 :compagnia => 'AM TRUST',
 :interlocutore => 'Pane',
 :area => 'Medical',
 },
{:canale_1 => 'Direzione Milano',
 :compagnia => 'SWISSE RE',
 :area => 'Medical',
 },
{:note_operative => 'Verificare apertura accordo',
 :canale_1 => 'Gerenza Bologna',
 :compagnia => 'REALE MUTUA',
 :area => 'Medical',
 },
{:canale_1 => 'Agenzia di Pesaro',
 :compagnia => 'GENERALI TORO',
 :interlocutore => 'Mancini',
 :area => 'Medical',
 },
]

more_companies.each do |company|
                   Company.create!(company)
end

# Director companies seeds

more_companies = [{:compagnia => 'ZURICH',
 :canale_1 => 'Dir. Milano',
 :interlocutore => 'Menapace / Provolo',
 :area => 'Director',
 },
{:note_operative => 'D&O
D&O+PI x Financial Institution',
 :compagnia => 'CNA',
 :canale_1 => 'Direzione Milano',
 :aggiornamento => DateTime.strptime('04/12/13', '%d/%m/%y'),
 :area => 'Director',
 },
{:portale => :true,
 :compagnia => ' ACE',
 :canale_1 => 'Direzione Padova / Milano',
 :area => 'Director',
 },
{:compagnia => 'LLOYD\'S LINK',
 :portale => :true,
 :area => 'Director',
 },
{:portale => :true,
 :compagnia => 'LLOYD\'S AEC',
 :canale_1 => 'Gerenza Roma',
 :area => 'Director',
 },
{:compagnia => 'QBE',
 :canale_1 => 'Gerenza Bologna',
 :aggiornamento => DateTime.strptime('14/10/13', '%d/%m/%y'),
 :note_operative => 'D&O',
 :area => 'Director',
 },
{:note_operative => '?? VERIFICARE OPERATIVITA\'',
 :compagnia => 'LLOYD\'S UIA',
 :canale_1 => 'Direzione Milano',
 :area => 'Director',
 },
{:canale_1 => 'Direzione Milano',
 :compagnia => 'DUAL',
 :portale => :true,
 :area => 'Director',
 },
{:compagnia => 'AIG',
 :area => 'Director',
 },
{:compagnia => 'CHUBB',
 :area => 'Director',
 },
{:compagnia => 'LLOYD\'S RFIB',
 :area => 'Director',
 },
{:note_operative => '?? VERIFICARE OPERATIVITA\'',
 :compagnia => 'LLOYD\'S SATEC',
 :area => 'Director',
 },
]

more_companies.each do |company|
                   Company.create!(company)
end

# Employment companies seeds

more_companies = [{:compagnia => 'ZURICH',
 :area => 'Employment',
 },
{:compagnia => 'CNA',
 :area => 'Employment',
 },
{:compagnia => ' ACE',
 :area => 'Employment',
 },
{:compagnia => 'LLOYD\'S LINK',
 :area => 'Employment',
 },
{:compagnia => 'LLOYD\'S AEC',
 :area => 'Employment',
 },
{:compagnia => 'QBE',
 :area => 'Employment',
 },
{:compagnia => 'LLOYD\'S UIA',
 :area => 'Employment',
 },
{:compagnia => 'DUAL',
 :area => 'Employment',
 },
{:note_operative => '* Aziende no USA;
* No sinistri ultimi 3 anni oltre € 10.000;No attive in Servizi Finanziari;
* Disponibile max € 2.500.000 di default;
* Consulenza serv. comunicazione Edelman fino ad € 10.000;
* 2 H di consulenza legale;
* Esperti investigativi;
* Costi di sostituzione del dipendente
* Costi pubblicazione sentenza',
 :brochure => 'Sì',
 :aggiornamento => DateTime.strptime('26/06/14', '%d/%m/%y'),
 :compagnia => 'AIG',
 :area => 'Employment',
 },
{:compagnia => 'CHUBB',
 :area => 'Employment',
 },
{:compagnia => 'LLOYD\'S RFIB',
 :area => 'Employment',
 },
{:compagnia => 'LLOYD\'S SATEC',
 :area => 'Employment',
 },
]

more_companies.each do |company|
                   Company.create!(company)
end

# Car companies seeds

more_companies = [{:canale_1 => 'Dir. Milano',
 :portale => :true,
 :compagnia => 'ZURICH',
 :interlocutore => 'Menapace / Provolo',
 :area => 'Car',
 },
{:portale => :true,
 :compagnia => 'ALLIANZ',
 :canale_1 => 'Direzione milano',
 :area => 'Car',
 },
{:canale_1 => 'Direzione Milano',
 :portale => :true,
 :compagnia => 'TUA',
 :area => 'Car',
 },
{:canale_1 => 'Direzione Padova',
 :compagnia => 'UNIPOL',
 :portale => :true,
 :area => 'Car',
 },
{:compagnia => 'FONDIARIA',
 :portale => :true,
 :canale_1 => 'Direzione Milano',
 :interlocutore => 'Papotti',
 :area => 'Car',
 },
{:canale_1 => 'Direzione Milano',
 :compagnia => 'AXA',
 :area => 'Car',
 },
{:compagnia => 'AXA',
 :canale_1 => 'Agenzia Reggio E',
 :area => 'Car',
 },
{:interlocutore => 'Carboni',
 :compagnia => 'AVIVA',
 :canale_1 => 'Agenzia Bologna',
 :area => 'Car',
 },
{:interlocutore => 'Turrini',
 :note_operative => 'Top cars',
 :compagnia => 'ALLIANZ',
 :canale_1 => 'Ag. Bologna Giardini',
 :area => 'Car',
 },
]

more_companies.each do |company|
                   Company.create!(company)
end

# Vehicle companies seeds

more_companies = [{:interlocutore => 'Guerrini',
 :portale => :true,
 :compagnia => 'FILO DIRETTO',
 :canale_1 => 'Dir. Milano',
 :area => 'Vehicle',
 },
{:note_operative => 'Max 50k senza satellitare; fino a 100k con satellitare',
 :portale => :true,
 :compagnia => 'AIG',
 :canale_1 => 'Direzione milano',
 :area => 'Vehicle',
 },
{:portale => :true,
 :compagnia => 'ZURICH',
 :canale_1 => 'Dir. Milano',
 :interlocutore => 'Menapace / Provolo',
 :area => 'Vehicle',
 },
{:compagnia => 'ALLIANZ',
 :portale => :true,
 :canale_1 => 'Direzione milano',
 :area => 'Vehicle',
 },
{:canale_1 => 'Direzione Milano',
 :portale => :true,
 :compagnia => 'TUA',
 :area => 'Vehicle',
 },
{:canale_1 => 'Direzione Padova',
 :portale => :true,
 :compagnia => 'UNIPOL',
 :area => 'Vehicle',
 },
{:compagnia => 'FONDIARIA',
 :portale => :true,
 :canale_1 => 'Direzione Milano',
 :interlocutore => 'Papotti',
 :area => 'Vehicle',
 },
{:canale_1 => 'Ag. Bologna Giardini',
 :compagnia => 'ALLIANZ',
 :note_operative => 'Top cars',
 :interlocutore => 'Turrini',
 :area => 'Vehicle',
 },
{:compagnia => 'NAT SUISSE',
 :note_operative => 'Top cars, SE in presenza di Fine Art',
 :area => 'Vehicle',
 },
{:note_operative => 'Solo flotte libri matricola',
 :interlocutore => 'Carnevali',
 :compagnia => 'CATTOLICA',
 :canale_1 => 'Direzione Milano',
 :area => 'Vehicle',
 },
{:compagnia => 'LLOYD\'S IO BROKER',
 :interlocutore => 'Vittorio Scala',
 :note_operative => 'Oltre 100k s.a. con satellitare',
 :area => 'Vehicle',
 },
]

more_companies.each do |company|
                   Company.create!(company)
end

# Legal companies seeds

more_companies = [{:compagnia => 'FILO DIRETTO',
 :portale => :true,
 :canale_1 => 'Dir. Milano',
 :interlocutore => 'Guerrini',
 :area => 'Legal',
 },
{:canale_1 => 'Direzione milano',
 :compagnia => 'ALLIANZ',
 :area => 'Legal',
 },
{:canale_1 => 'Direzione Milano',
 :compagnia => 'ROLAND',
 :interlocutore => 'Pipotone',
 :area => 'Legal',
 },
{:canale_1 => 'Direzione Milano',
 :portale => :true,
 :compagnia => 'EUROP ASSITANCE',
 :area => 'Legal',
 },
{:compagnia => 'UCA',
 :portale => :true,
 :canale_1 => 'Direzione Torino',
 :area => 'Legal',
 },
{:portale => :true,
 :compagnia => 'ARAG',
 :canale_1 => 'Direzione Verona',
 :area => 'Legal',
 },
{:compagnia => 'TUTELA PIREDDA',
 :area => 'Legal',
 },
]

more_companies.each do |company|
                   Company.create!(company)
end

# Nonprofit companies seeds

more_companies = [{:compagnia => 'LLOYD\'S IO BROKER',
 :interlocutore => 'Andrea Porro',
 :area => 'Nonprofit',
 },
]

more_companies.each do |company|
                   Company.create!(company)
end

# Benefit companies seeds

more_companies = [{:compagnia => 'ALLIANZ',
 :aggiornamento => DateTime.strptime('25/03/14', '%d/%m/%y'),
 :canale_1 => 'Direzione Padova',
 :note_operative => 'Cassa di assistenza Allianz (Previp)
Contraenza Azienda con fatturato minimo 4mln€
Categoria/e completa/e (tutti Impiegati Amministrativi, tutti Dirigenti, tutti….) – estendibile a tutte le famiglie:
- 7 tipologie/livelli di prestazioni
-  Integrativa FASI – con gestione diretta della prestazione anche presso Fasi
-  Minimo 5 teste (categoria completa) – estendibile a famiglia',
 :area => 'Benefit',
 },
]

more_companies.each do |company|
                   Company.create!(company)
end

# Installation companies seeds

more_companies = [{},
]

more_companies.each do |company|
                   Installation.create!(company)
end

